### ISSUE TITLE
How to use without slimproto part

### ISSUE THREAD

**Issue by ronan-ln** [gimesketvirtadieni/slimstreamer#1]
Hi,

I am very interested by this project, as I'd like to be able to broadcast the sound coming out of my Kodi instance (running with OSMC through ALSA) to other squeezebox clients.
I have been trying by combining asound.conf with the WaveInput plugin for Logitech Media Server but couldn't get it to work.
I am also looking for a setup that would allow for the sound to be played through the system speakers AND broadcast. 

You mention that you have been testing SlimStreamer with the Logitech Media Server as intermediary while you are working on the streaming part. Do you have instructions on how to do that? How do you load and use the ALSA plugin?

Thanks,
Ronan

**Comment by dhtek** [comment]
Hello,

It's a really great project that you have started...Like Ronan, I would like to try your system and give my feedback. 

Thanks for your job

**Comment by gimesketvirtadieni** [comment]
Hi,
Thanks for your questions; it is great to see people getting interested in SlimStreamer :)
Ronan, I think streaming sound from Kodi through SlimStreamer to Squeezebox players (like squeezelite) will work (once I get it working end-2-end). There is no need for any Kodi tailoring, it will not even notice that PCM data being captured and streamed. In addition, it should be fairly easy to route PCM to both SlimPlexor (which will pass it on to SlimStreamer) and to local system device (through ALSA tee plugin). However, the result might be not what you are expecting.
I guess you want to play all players in-sync (otherwise, you hear echo or cacophony :) There is no way to sync system device (being feed directly through tee plugin) with Squeezebox player (like squeezelite). It means you would have to run squeezelite locally; it will receive PCM data from SlimStreamer just like the rest of Squeezebox players. This way it would be possible to achieve in-sync playback of the host and remote players (although I have not tried a setup like this).
However, there is one more important challenge to overcome: synchronization with video. I expect playback latency (time duration between start was presses and actual playback starts on players) in case of SlimStreamer will be around 1 sec. In network streaming domain it would be a great achievement (normally latency would be around 2 sec. or even more). In other words, video will be ahead of audio by a value of playback latency. Potentially it should be possible to configure Kodi to “delay” video by 1 sec. To make it work, SlimStreamer would need to guaranty that playback latency is constant, now it is not the case yet.
On the bright side, humans are not good in detecting drift between video and audio (on the contrary, humans are very good in detecting drift in two audio sources). So eventually, it should be possible to use SlimStreamer in combination with Kodi.
Finally, current synchronisation solutions used for network audio streaming (to my knowledge) do not achieve accuracy required for streaming different channels to different network players (think of surround sound over WiFi). Situation will change after Wi-Fi TimeSync is adopted be HW manufactures.
Ronan, could you explain more about your use case? It will help me to understand how much is still missing ;)

**Comment by ronan-ln** [comment]
Hi
I think you have summarised most of my requirements.
Regarding syncing, I am not so bothered about having audio synced between
system (Kodi) and the players, but I am considering following your approach
of having Kodi output to a loopback device, and the sound coming out of a
local squeezelite player (to my speakers). Would it be a challenge to
implement constant latency to support this?
One thing that I would like to be able to do is change the volume or mute
sound from Kodi without affecting the streamed output. It seems like it
would mean Kodi outputting to q device (loopback), but controlling another
(hw soundcard). Is that possible with an ALSA config?

It sounds like I should be able to try something with the parts that are
already done. Would you mind explaining how to use your code to get the
SlimPlexor setup? Is it an asound.conf configuration using the loopback
device? I assume that should give me some output using arecord or the
WaveInput plugin?

Thanks,
Ronan

On Dec 29, 2017 1:48 PM, "gimesketvirtadieni" <notifications@github.com>
wrote:

Hi,
Thanks for your questions; it is great to see people getting interested in
SlimStreamer :)
Ronan, I think streaming sound from Kodi through SlimStreamer to Squeezebox
players (like squeezelite) will work (once I get it working end-2-end).
There is no need for any Kodi tailoring, it will not even notice that PCM
data being captured and streamed. In addition, it should be fairly easy to
route PCM to both SlimPlexor (which will pass it on to SlimStreamer) and to
local system device (through ALSA tee plugin). However, the result might be
not what you are expecting.
I guess you want to play all players in-sync (otherwise, you hear echo or
cacophony :) There is no way to sync system device (being feed directly
through tee plugin) with Squeezebox player (like squeezelite). It means you
would have to run squeezelite locally; it will receive PCM data from
SlimStreamer just like the rest of Squeezebox players. This way it would be
possible to achieve in-sync playback of the host and remote players
(although I have not tried a setup like this).
However, there is one more important challenge to overcome: synchronization
with video. I expect playback latency (time duration between start was
presses and actual playback starts on players) in case of SlimStreamer will
be around 1 sec. In network streaming domain it would be a great
achievement (normally latency would be around 2 sec. or even more). In
other words, video will be ahead of audio by a value of playback latency.
Potentially it should be possible to configure Kodi to “delay” video by 1
sec. To make it work, SlimStreamer would need to guaranty that playback
latency is constant, now it is not the case yet.
On the bright side, humans are not good in detecting drift between video
and audio (on the contrary, humans are very good in detecting drift in two
audio sources). So eventually, it should be possible to use SlimStreamer in
combination with Kodi.
Finally, current synchronisation solutions used for network audio streaming
(to my knowledge) do not achieve accuracy required for streaming different
channels to different network players (think of surround sound over WiFi).
Situation will change after Wi-Fi TimeSync is adopted be HW manufactures.
Ronan, could you explain more about your use case? It will help me to
understand how much is still missing ;)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gimesketvirtadieni/slimstreamer/issues/1#issuecomment-354448111>,
or mute the thread

**Comment by gimesketvirtadieni** [comment]
Hi,

I need to complete end-2-end flow in order to measure the latency. Next step would be building functionality to make sure it is constant so audio can be synced with video by delaying video in Kodi. It sounds like a fun task :)

SlimPlexor does two things: it adds one more channel with meta data about PCM stream (this extra channel is removed afterwards by SlimStreamer). Also it redirects PCM stream to a predefined loopback device so that SlimStreamer 'knows' the sample rate. SlimPlexor is not usable apart from SlimPlexor, although it is C code, which is quite simplistic so you are welcome to use it for tailoring.

I heard about WaveInput plugin, but did not have a need for setting it up, I am sorry, cannot help you with it.

**Comment by ronanln** [comment]
Hi,
What do you mean when you say that "SlimPlexor is not usable apart from SlimPlexor"?
I assumed that with it being an ALSA plugin, I would be able to add it to my ALSA setup and set up the configuration in asound.conf?
I make use of my LMS server at the moment, so you have already developed the parts of the project that I am most interested in!
Could you give some details and steps of how to set them up to get something out of it? Before you started developing the SlimProto component you mentioned you had all other parts ready. How were you outputting sound at that point?

**Comment by gimesketvirtadieni** [comment]
Hello Ronan

Thanks for pointing a typo in my comment. I had in mind that SlimPlexor is not usable without _SlimStreamer_ (I corrected this typo in my original comment).
I added a sample asound.conf file into SlimPlexor repo on github (please check 'misc' directory). It will give you an understanding about ALSA setup (although using asound.conf is not enough, there are additional steps required to enable loopback devices).
The way I validated that PCM capture and delivery to SlimStreamer in a bit-perfect way works is that SlimStreamer is able to 'dump' PCM stream into a WAVE file. This way I can see what was received from audio producer. If I know what it is sending then I can validate against the actual output in WAVE file.
I have made a good progress over the last few weeks and managed to get sound all the way: Original App->SlimPlexor->Loopback->SlimStreamer->squeezelite->DAC. The 'sound' I am getting at the moment is a 'white noice', but I am quite sure it is due to incorrect byte order while sending over the network. In other words I should be able to complete ALPHA version within a week or two (that includes instructions how to set things up).
Please let me know if you have further questions ;)

**Comment by gimesketvirtadieni** [comment]
Hi

It works! ... With many hardcoded values, only for 44.1 Khz, without synchronization, with unhandled errors... But it works! All the way: from an arbitrary application playing musing to a default ALSA device to squeezelite application used for normal playback.
Now I will focus on making it usable for regular users (alpha version).
I must admit it will be without synchronization initially, but it will come a bit later ;)

**Comment by ronan-ln** [comment]
Great! I look forward to alpha test it.

**Comment by gimesketvirtadieni** [comment]
Hello guys

I published instructions how to build [SlimPlexor](https://github.com/gimesketvirtadieni/slimplexor) and set up ALSA for PCM capture. Please try it out and let me know if you managed to succeed. Any comments about how to make description more user-friendly is much appreciated ;)

**Comment by gimesketvirtadieni** [comment]
Hi

Quick update: I have just prepared Alpha release with compiled binaries, so no need to compile anything (for amd64 and armhf architectures). Anyone willing to give it a try?

**Comment by ronan-ln** [comment]
Hi there,
I have tried your latest release and managed to get it to work fine on a test setup.
I am working on the Rapsberry Pi (running OSMC) and the binaries for that worked fine. Instructions were easy to follow as well.
There are 2 points which I have had issues with which I would like to investigate more.
1/ I use a HifiBerry Amp+ on my "production" system. I'm not sure if that's the reason, but the slimstreamer->squeezelite didn't produce any results on this system. I will try further.

2/ The Squeezebox classic device that I have could not detect the slimstreamer server on my network, so I wasn't able to confirm that sound could be output there too. Do you have access to one of these devices yourself? I was hoping to mimic a slimproto HTTP server to try and get this working. Do you have links to the Slimproto specifications?

3/ As you mention, it looks like there are still things hardcoded in the code. Could you make these be set with command line arguments instead? (I'm thinking about the server port and sound devices especially).

Thanks for the great work! I hope I can help make it even better :)

**Comment by gimesketvirtadieni** [comment]
Hi Ronan

Great you got it working... You are right, there is no discovery at the moment, also port numbers are hard coded. Let's track them through dedicated issues. Let me know if you disagree ;)
